### ISSUE TITLE
Android Basics: Persist data with Room - Build output error

### ISSUE THREAD

**Issue by Andy-Cuong** [google-developer-training/android-basics-kotlin-inventory-app#44]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-persisting-data-room

**In which task and step of the codelab can this issue be found?**
Probably step 6 and in step 9 when running the code

**Describe the problem**
Build output shows a lot of error when running such as annotation and return type of the functions in DAO, specifically:

- error: Type of the parameter must be a class annotated with @Entity or a collection/array of it.
     kotlin.coroutines.Continuation<? super kotlin.Unit> continuation);
 
- error: Not sure how to handle insert method's return type.
     public abstract java.lang.Object insert(@org.jetbrains.annotations.NotNull()

- error: Not sure how to handle delete method's return type. Currently the supported return types are void, int or Int.
     public abstract java.lang.Object delete(@org.jetbrains.annotations.NotNull()
 
- error: Type of the parameter must be a class annotated with @Entity or a collection/array of it.
     kotlin.coroutines.Continuation<? super kotlin.Unit> continuation);
 
- error: Type of the parameter must be a class annotated with @Entity or a collection/array of it.
     kotlin.coroutines.Continuation<? super kotlin.Unit> continuation);

- error: Not sure how to handle update method's return type. Currently the supported return types are void, int or Int.
     public abstract java.lang.Object update(@org.jetbrains.annotations.NotNull()

**Versions**
_Android Studio version:_ Chipmunk 2021.2.1
_API version of the emulator:_ API 31

**Additional information**
![image](https://user-images.githubusercontent.com/94699066/173933805-b4115eec-568d-4f34-bde4-0f8c1b2cd65d.png)

**Comment by shepardsn** [comment]
I ran into the same issue.  For me it turned out to be the versions of Room and Kotlin plugin I was using in Android Studio weren't compatible.  It looks like you need to use the version of Kotlin that Room has been updated for.

You can look at the release notes for the versions to see roughly which version of Kotlin to use.  eg.  

For instance in the release notes for [2.4.0-rc01](https://developer.android.com/jetpack/androidx/releases/room#2.4.0-rc01) you can see this comment:
_Update Room’s dependency on KSP to 1.6.0-1.0.1 to support Kotlin 1.6_

which should be that the stable version of Room (eg. 2.4.2) should work with the Kotlin plugin 1.6.x. (and it does)


https://stackoverflow.com/questions/70241165/room-error-type-of-the-parameter-must-be-a-class-annotated-with-entity-or-a-co

**Comment by Andy-Cuong** [comment]
Thank you for clarifying it. I figured it out (partly thanks to @lbrooks2500 in [this issue](https://github.com/google-developer-training/android-basics-kotlin-inventory-app/issues/36)) that I should use the alpha version of Room aka [2.5.0-alpha02](https://developer.android.com/jetpack/androidx/releases/room#2.5.0-alpha02) for the _kapt "androidx.room:room-compiler"_ version so that it will be able to build, although other dependencies work fine with the stable version 2.4.2.

My current Kotlin version is 1.7.0, seemingly the latest stable one, so I assume I should stick with it. Seems like it is a matter of compatibility with Room compiler and Kotlin library
